apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: peerprep
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: asia-southeast1-docker.pkg.dev/peerprep-438213/peerprep/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          envFrom:
            - secretRef:
                name: peerprep-secrets
            - configMapRef:
                name: auth-configmap
      restartPolicy: Always
